---
title: "Analysis 1 Tracker"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(tidyverse)
```

Row
-----------------------------------------------------------------------

### Total Accessions

```{r}
# read in combined table
analysis_accession_list <- read.delim("02_middle-analysis_outputs/analysis_tables/genera_analysis_combined.tsv")
filtered_accession_list <- filter(analysis_accession_list, assembly_status != "suppressed") %>% count()
valueBox(filtered_accession_list$n, caption = "Total accessions", icon="fa-frog")
# icon and colour come from fontawesome

```

### Annotated

```{r}
annotated_files <- data.frame(filename = list.files("02_middle-analysis_outputs/eggnog_stuff/eggnog_outputs", pattern = "*.xlsx"))
annotated_files$accession <- sub("\\.(emapper).*", "", annotated_files$filename)

annotated_file_count <- filter(annotated_files, annotated_files$accession %in% analysis_accession_list$accession) %>% count()

valueBox(annotated_file_count$n, caption = "Accessions annotated", icon="fa-egg")
```

### Enriched

```{r}
enriched_files <- data.frame(filename = list.files("02_middle-analysis_outputs/eggnog_stuff/eggnog_outputs", pattern = "*.tsv"))
enriched_files$accession <- sub("\\_ko_enrichment.tsv", "", enriched_files$filename)

enriched_file_count <- filter(enriched_files, enriched_files$accession %in% analysis_accession_list$accession) %>% count()

valueBox(enriched_file_count$n, caption = "Accessions enriched", icon="fa-piggy-bank")
# icon and colour come from fontawesome

```

<!-- Column {data-width=350} -->
<!-- ----------------------------------------------------------------------- -->

<!-- ### Chart B -->

<!-- ```{r} -->

<!-- ``` -->

<!-- ### Chart C -->

<!-- ```{r} -->

<!-- ``` -->

