project:
  type: book

book:
  title: "ENS-2002 Research Experience Portfolio"
  author: "Tobias Nunn"
  date: "2025-04-22"
  chapters:
    - index.qmd
    - intro.qmd
    - summer_work.qmd
    - checkm.qmd
    - checkm2.qmd
    - gtdbtk_classify.qmd
    - gtdbtk_denovo.qmd
    - ncbi.qmd
    - eggnogmapper_proto.qmd
    - eggnogmapper_final.qmd
    - heatmaps.qmd
    - subprojects.qmd
    - flye_outs.qmd
    - gen_prog.qmd
    - summary.qmd
    - references.qmd
  repo-url: https://github.com/tobiasnunn/tnunn_research/tree/main/Research_Experience_Module/07_portfolio
  repo-branch: main
  repo-actions: [issue]
  sidebar:
    search: false

bibliography: references.bib

format:
  html:
    theme: cosmo
  docx:
    toc: true
    number-sections: true
    highlight-style: github

editor:
  render-on-save: true



