# Conclusion

The main result from this project is the heatmap from @sec-eggnogfull, which identified functional differences between genera. The pathways found in this chapter can be analysed in the context of past literature to infer their use to the bacteria they come from and the host and microbiome at large. Many secondary analyses were performed on the samples in order to explore them, and explore the tools themselves.

The creation of all the analyses, tables and visuals necessitated the use of a wide variety of computational tools. For example, the development of capabilities in R. However, this project also required development in other areas, such as command-line code and bash scripting. I now also understand how to use genomic tools such as GTDB-Tk [@chaumeil_gtdb-tk_2022]. These are important skills for a bioinformatician. However, most importantly, the requirement to keep a notebook and present my research in this manner are crucial skills for a career in zoology, and perhaps the greatest growth seen is in these fields of presentation, organisation and discipline. These skills gained here will become almost immediately useful as this study is built upon for my dissertation.

There are many ways this work can be built upon. For example, grouping by geographic range, akin to work done by @marzinelli_continental-scale_2015 . Hosts have been found to have core symbionts [@parfrey_introduction_2018]. Thus, a correlative study of hosts and bacterial species could prove interesting. Phylogeny and taxonomy are other useful tools of studying variation [@washburne_methods_2018]. Adding more genera to study and understanding the evolutionary distances between genera could provide fruitful analyses. An understanding of the samples is important for study. For example, through programs like CheckM2 [@chklovski_checkm2_2023]. As such, literature can be reviewed for potential future avenues of exploration and expand my knowledge on the area, to allow for more complex and meaningful analysis going forward.
